name: Run Datadog Synthetic tests
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]   # <-- ajusta si usas master
  pull_request:
    branches: [ "main" ]   # O evita PRs desde forks si necesitas secrets

jobs:
  run-synthetics:
    runs-on: ubuntu-latest
    # environment: production   # <-- si tus secrets están en un Environment
    steps:
      - uses: actions/checkout@v4

      - name: Assert Datadog secrets exist
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
        run: |
          if [ -z "$DD_API_KEY" ] || [ -z "$DD_APP_KEY" ]; then
            echo "Missing Datadog secrets. Define DD_API_KEY and DD_APP_KEY."
            exit 1
          fi

      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@87b505388a22005bb8013481e3f73a367b9a53eb # v1.4.0
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          app_key: ${{ secrets.DD_APP_KEY }}
          # datadog_site: datadoghq.eu   # si aplica
          test_search_query: 'tag:e2e-tests'